name: "DB Operations"
description: "Reusable PostgreSQL database operations"
inputs:
  PGHOST:
    description: "Database host"
    required: true
  PGPORT:
    description: "Database port"
    required: true
  PGUSER:
    description: "Database user"
    required: true
  PGPASSWORD:
    description: "Database password"
    required: true
  PGDATABASE:
    description: "Database name"
    required: true
  SCRIPT:
    description: "Python script to execute"
    required: true
runs:
  using: "composite"
  steps:
    - name: Execute database script
      env:
        PGHOST: ${{ inputs.PGHOST }}
        PGPORT: ${{ inputs.PGPORT }}
        PGUSER: ${{ inputs.PGUSER }}
        PGPASSWORD: ${{ inputs.PGPASSWORD }}
        PGDATABASE: ${{ inputs.PGDATABASE }}
      run: |
        echo "${{ inputs.SCRIPT }}" > script.py
        python script.py
