name: postgressdb

on:
  workflow_dispatch:
    inputs:
      sql_file_path:
        description: 'Path to the SQL file'
        required: true
        default: 'database/databaseSelectQueries.sql'
        
jobs:
  HealthCheck:
    runs-on: ubuntu-latest
    env:
      PGHOST: ${{ secrets.DB_HOSTNAME }}
      PGPORT: ${{ secrets.DB_PORT }}
      PGUSER: ${{ secrets.DB_USER }}
      PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      PGDATABASE: ${{ secrets.DB_DATABASE }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: CRUD Operation On edgeConnect-Config
        run: |
          echo "import os
          import psycopg2
          conn = psycopg2.connect(
              host=os.getenv('PGHOST'),
              port=os.getenv('PGPORT'),
              user=os.getenv('PGUSER'),
              password=os.getenv('PGPASSWORD'),
              dbname=os.getenv('PGDATABASE')
          )
          cur = conn.cursor()
          sql_file_path = '${{ github.event.inputs.sql_file_path }}'
          with open(sql_file_path, 'r') as file:
              sql = file.read()
              cur.execute(sql)
          conn.commit()
          cur.close()
          conn.close()" > run_sql_script.py
          python run_sql_script.py
