name: postgressdb

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'insert'
        type: choice
        options:
          - insert
          - select

jobs:
  HealthCheck:
    runs-on: ubuntu-latest

    env:
      PGHOST: ${{ secrets.DB_HOSTNAME }}
      PGPORT: ${{ secrets.DB_PORT }}
      PGUSER: ${{ secrets.DB_USER }}
      PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      PGDATABASE: ${{ secrets.DB_DATABASE }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Start PostgreSQL service
        run: |
          docker run -d \
            -e POSTGRES_DB=$PGDATABASE \
            -e POSTGRES_USER=$PGUSER \
            -e POSTGRES_PASSWORD=$PGPASSWORD \
            -p $PGPORT:$PGPORT \
            --name postgres-container \
            postgres:14
          # Wait for PostgreSQL to be ready
          until docker exec postgres-container pg_isready; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Connect to PostgreSQL
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          print('Connected to the database')
          conn.close()" > test_db_connection.py
          python test_db_connection.py

      - name: Insert Tables To edgeConnect-Config
        if: ${{ github.event.inputs.action == 'insert' }}
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          cur = conn.cursor()
          with open('database/insert/insertQueries.sql', 'r') as file:
              sql = file.read()
              cur.execute(sql)
          conn.commit()
          cur.close()
          conn.close()" > run_sql_script.py
          python run_sql_script.py

      - name: Select Employee Tables from PostgreSQL
        if: ${{ github.event.inputs.action == 'select' }}
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          cur = conn.cursor()
          cur.execute('select * from pocaws.employeetable')
          rows = cur.fetchall()
          for row in rows:
              print(row)
          cur.close()
          conn.close()" > select_data.py
          python select_data.py
