name: postgressdb
run-name: Setting up the Postgress Database
on: [push]
jobs:
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show databases
      run: mysql -h ${{ secrets.DB_HOSTNAME }} --port 5432 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES";
  
