name: Insert Data into PostgreSQL

on:
  push:
    branches:
      - main  # adjust based on your branch

jobs:
  insert-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        uses: docker://postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: EdgeOne!
          POSTGRES_DB: postgres

      - name: Run SQL script
        run: |
          psql -h database-1.cb83vc84s1ku.us-east-1.rds.amazonaws.com -U postgres -d postgres -f insertQueries.sql

