name: postgressdb
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  HealthCheck:
    runs-on: ubuntu-latest
 
    services:
      postgres:
        image: postgres:14
        ports:
          - ${{secrets.DB_PORT}}:${{secrets.DB_PORT}}
        env:
          POSTGRES_DB: ${{secrets.DB_DATABASE}}
          POSTGRES_USER: ${{secrets.DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary
 
      - name: Run script to connect to PostgreSQL
        env:
          PGHOST: ${{secrets.DB_HOSTNAME}}
          PGPORT: ${{secrets.DB_PORT}}
          PGUSER: ${{secrets.DB_USER}}
          PGPASSWORD: ${{secrets.DB_PASSWORD}}
          PGDATABASE: ${{secrets.DB_DATABASE}}
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          print('Connected to the database')
          conn.close()" > test_db_connection.py
          python test_db_connection.py
 
      - name: Run SQL script
        env:
          PGHOST: ${{secrets.DB_HOSTNAME}}
          PGPORT: ${{secrets.DB_PORT}}
          PGUSER: ${{secrets.DB_USER}}
          PGPASSWORD: ${{secrets.DB_PASSWORD}}
          PGDATABASE: ${{secrets.DB_DATABASE}}
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          cur = conn.cursor()
          with open('insertQueries.sql', 'r') as file:
              sql = file.read()
              cur.execute(sql)
          conn.commit()
          cur.close()
          conn.close()" > run_sql_script.py
          python run_sql_script.py
 
      - name: Run script to Select Employee Tables to PostgreSQL
        env:
          PGHOST: ${{secrets.DB_HOSTNAME}}
          PGPORT: ${{secrets.DB_PORT}}
          PGUSER: ${{secrets.DB_USER}}
          PGPASSWORD: ${{secrets.DB_PASSWORD}}
          PGDATABASE: ${{secrets.DB_DATABASE}}
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          cur = conn.cursor()
          cur.execute('select * from pocaws.employeetable')
          rows = cur.fetchall()
          for row in rows:
              print(row)
          cur.close()
          conn.close()" > select_data.py
          python select_data.py
