name: postgressdb

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: EdgeOne!
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          while ! pg_isready -h localhost -p 5432 -U test_user; do
            sleep 1
          done
          echo "PostgreSQL is ready"

      - name: Run script to connect to PostgreSQL
        env:
          PGHOST: database-1.cb83vc84s1ku.us-east-1.rds.amazonaws.com
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: EdgeOne!
          PGDATABASE: postgres
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          print('Connected to the database')
          conn.close()" > test_db_connection.py
          python test_db_connection.py

      - name: Run script to Insert Employee Tables to PostgreSQL
        env:
          PGHOST: database-1.cb83vc84s1ku.us-east-1.rds.amazonaws.com
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: EdgeOne!
          PGDATABASE: postgres
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          cur = conn.cursor()
          cur.execute(\"INSERT INTO pocaws.employeetable (empname, empid) VALUES ('Alice_10', 10)\")          
          conn.commit()
          cur.close()
          conn.close()" > insert_data.py
          python insert_data.py

      - name: Run script to Select Employee Tables to PostgreSQL
        env:
          PGHOST: database-1.cb83vc84s1ku.us-east-1.rds.amazonaws.com
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: EdgeOne!
          PGDATABASE: postgres
        run: |
          echo "import psycopg2
          conn = psycopg2.connect(
              host='$PGHOST',
              port='$PGPORT',
              user='$PGUSER',
              password='$PGPASSWORD',
              dbname='$PGDATABASE'
          )
          cur = conn.cursor()
          cur.execute('select * from pocaws.employeetable')
          rows = cur.fetchall()
          for row in rows:
              print(row)
          cur.close()
          conn.close()" > select_data.py
          python select_data.py          
          
