name: postgressdb

on:
  workflow_dispatch:
    inputs:
      sql_directory:
        description: 'Path to the directory containing SQL files'
        required: true
        default: 'database'
        
jobs:
  HealthCheck:
    runs-on: ubuntu-latest
    env:
      PGHOST: ${{ secrets.DB_HOSTNAME }}
      PGPORT: ${{ secrets.DB_PORT }}
      PGUSER: ${{ secrets.DB_USER }}
      PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      PGDATABASE: ${{ secrets.DB_DATABASE }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Set SQL directory
        run: echo "SQL_DIRECTORY=${{ github.event.inputs.sql_directory }}" >> $GITHUB_ENV

      - name: CRUD Operation On edgeConnect-Config
        run: |
          echo "import os
          import psycopg2
          import glob

          conn = psycopg2.connect(
              host=os.getenv('PGHOST'),
              port=os.getenv('PGPORT'),
              user=os.getenv('PGUSER'),
              password=os.getenv('PGPASSWORD'),
              dbname=os.getenv('PGDATABASE')
          )
          cur = conn.cursor()
          sql_directory = os.getenv('SQL_DIRECTORY')
          print(f'Reading SQL files from directory: {sql_directory}')

          sql_files = glob.glob(os.path.join(sql_directory, '**', '*.sql'), recursive=True)
          for sql_file in sql_files:
              print(f'Executing SQL file: {sql_file}')
              with open(sql_file, 'r') as file:
                  sql = file.read()
                  cur.execute(sql)
                  conn.commit()

          cur.close()
          conn.close()" > run_sql_script.py
          python run_sql_script.py
